// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rubfqysrwzqidxbkewpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1YmZxeXNyd3pxaWR4Ymtld3BtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NzE5NTgsImV4cCI6MjA3MTQ0Nzk1OH0.9QTnlHvuw2AaMjjdZsBH0IiUt3egjP7QBJG0fdOXjRI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});